[project]
name = "mesa"
version = "0.1.0"
description = "Add a short description here"
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["main", "r", "msys2", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
vegetation = "solara run vegetation/app.py"

[dependencies]
python = "3.11.*"
pytest = "*"
debugpy = "*"
ipython = "*"
python-dotenv = "*"
planetary-computer = "*"
pystac-client = "*"
scipy = "*"
numpy = "*"
pandas = "*"
stackstac = "*"
geopandas = "*"
rioxarray = "*"
networkx = "3.3"
matplotlib = "*"
typing-extensions = ">=4.12.0rc1"
sqlite = "*"
solara = "*"
pip = "*"
<<<<<<< HEAD
zarr = ">3"
xarray = "*"
gcsfs = "*"
imageio = "*"
=======
zarr = ">=2.13.3,<3"
xarray = ">=2024.11.0,<2025"
gcsfs = ">=2024.12.0,<2025"
imageio = ">=2.37.0,<3"
dill = ">=0.3.8,<0.4"
>>>>>>> parent of e7e96d9 (zarr version issues.... runnning into issue with numpy prod vs numpy product, the latter is deprecated. Going to see if upgrading to next major version will break everything)

[pypi-dependencies]
mesa = { version = "==3.1.1" }
mesa-geo = { version = "==0.9.0" }
