[project]
name = "mesa"
version = "0.1.0"
description = "Add a short description here"
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["main", "r", "msys2", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
python = "3.10.*"
debugpy = "*"
ipython = "*"
python-dotenv = "*"
planetary-computer = "*"
pystac-client = "*"
scipy = "*"
numpy = "*"
pandas = "*"
stackstac = "*"
geopandas = "*"
rioxarray = "*"
networkx = "*"
matplotlib = "*"
typing-extensions = ">=4.12.0rc1"
sqlite = "*"
pip = "*"

[target.linux-64.pypi-dependencies]
mesa = "*"
mesa-geo = { version = "==0.9.0a1" }
solara = "*"
