[project]
name = "mesa"
version = "0.1.0"
description = "Add a short description here"
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["main", "r", "msys2", "conda-forge"]
platforms = ["linux-64"]

[tasks]
vegetation = "solara run vegetation/app.py"

[dependencies]
pytest = ">=7.4.4,<7.5"
black = ">=24.8.0,<24.9"

[target.linux-64.dependencies]
python = "3.11.*"
debugpy = "*"
ipython = "*"
python-dotenv = "*"
planetary-computer = "*"
pystac-client = "*"
scipy = "*"
numpy = "1.24.*"
pandas = "*"
stackstac = "*"
geopandas = "*"
rioxarray = "*"
networkx = "3.3"
matplotlib = "*"
typing-extensions = ">=4.12.0rc1"
sqlite = "*"
solara = "*"
pip = "*"


[target.linux-64.pypi-dependencies]
mesa = { version = "==3.1.1" }
mesa-geo = { version = "==0.9.0" }
