name: mesa
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - debugpy
  - ipython
  - python-dotenv
  - scipy
  - numpy
  - pandas
  - mesa
  - mesa-geo
  - solara
  - sqlite
  - pip
