name: "Run pytest with Pixi env"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.5
          environments: default
          activate-environment: true
          frozen: true
      - run: pytest -v tests/